### ISSUE TITLE
A presentation request builder + Store presentation templates

### ISSUE THREAD

**Issue by hiteshgh** [bcgov/DITP#20]
A presentation request builder + Store presentation templates

**Comment by esune** [comment]
Might relate to [this](https://github.com/bcgov/bc-wallet-mobile/issues/800).

**Comment by swcurran** [comment]
IMHO — we don’t want a presentation request builder.  What we want is a data structure that has an embedded presentation request, with elements that can be templatized — e.g. selected claims to reveal or not reveal, an age to check in a predicate (“older than 19”, where 19 is the templatized/parameterized value).  

Related to this comment: https://github.com/bcgov/bc-wallet-mobile/issues/800#issuecomment-1402878712

**Comment by esune** [comment]
> 
Thanks @swcurran . I was thinking something among the lines of a "directory" of pre-curated proof-requests (e.g.: holds a Canadian form of ID and is over 19) that could be used, as well as *potentially* (not yet sure about this) combining more than one of these proofs into one (this could be helpful for non-power users to pick a template and provide it to their dev team).

**Comment by swcurran** [comment]
I think that combining proofs from multiple templates in some kind of automated fashion would be extremely difficult. For that, I would suggest a service request model where a business owner would request in plain language what they want, and a developer might build the required template.

**Comment by ianco** [comment]
I agree with @swcurran

**Comment by esune** [comment]
I agree, although I don't think that combining a couple of *simple* proof requests would be extremely difficult (it would mostly be getting the restrictions blocks and combining them). What is described in https://github.com/bcgov/bc-wallet-mobile/issues/800#issuecomment-1402878712 on the other hand seems very neat, but extremely complicated.

Either way, no need to poke more into this service if deemed non-useful at this time.

**Comment by esune** [comment]
Closing as this was deemed unnecessary at this time. A new issue can be logged if/when appropriate.
