### ISSUE TITLE
Ian's Transition / Knowledge Transfer

### ISSUE THREAD

**Issue by esune** [bcgov/DITP#25]
Knowledge transfer for items usually managed by @ianco, such as:
- BC Registries (business and issuer)
  - The upcoming BC Registries Upgrade
- ACA-Py Demo — details and updating
- ACA-Py Integration Tests — architecture, updating, extending
- ACA-Py PR Reviews and community support

**Comment by ianco** [comment]
- Aca-py integration tests
- AATH (Sheldon knows this so maybe not a priority)
- aries-loadgenerator (Wade King has looked at this so maybe not a priority)

(I see @esune is adding new topics even as I write this)

**Comment by ianco** [comment]
I suggest we book 2 sessions of 90 minutes each:
- one for Aries-VCR, BC Reg issuer and all related repo's, 
- and the other for aca-py related stuff, including AATH, load generator, etc
The next 2 Friday afternoons, 2:30 to 4pm?
@esune @swcurran
