### ISSUE TITLE
Please create repo -- aries-oca-bundles

### ISSUE THREAD

**Issue by swcurran** [bcgov/DITP#27]
Please create the repo and add myself, @WadeBarnes and @amanji as maintainers.  Please activate DCO on the repo.  I'll add content as soon as the repo is created.

**Comment by swcurran** [comment]
Let me know if you need anything else.

**Comment by WadeBarnes** [comment]
Done; https://github.com/bcgov/aries-oca-bundles

**Comment by swcurran** [comment]
Thanks
