### ISSUE TITLE
Unable to run Wallet behind firewall

### ISSUE THREAD

**Issue by cvarjao** [bcgov/DITP#29]
Mobile wallet apps needs access to ledger data (DIDDOC, Revocation Registry, ...). Access to ledgers are done via ZMQ on port 9702. That port is usually blocked in corporate firewalls.

Blocking:
-  bcgov/bc-wallet-mobile#403

**Comment by WadeBarnes** [comment]
See my comments regarding the indy-node port range here; https://github.com/bcgov/bc-wallet-mobile/issues/403#issuecomment-1564440409

and the specifics of opening the ports here;  https://github.com/bcgov/bc-wallet-mobile/issues/403#issuecomment-1564455941

**Comment by esune** [comment]
@WadeBarnes do we need to do anything or the comments you added in the BC Wallet repo are sufficient to close this?

**Comment by WadeBarnes** [comment]
The comments I added (linked) to the BC Wallet repo address this issue.
