### ISSUE TITLE
Prepare a reusable, 1.5 hour “verifier” technical workshop that we’ll use with CoV on September 5

### ISSUE THREAD

**Issue by swcurran** [bcgov/DITP#33]
We’ll do this in conjunction with the Delivery team, and using a sandbox instance of Traction.

Initial tasks to be done:

* [ ] Decide on the goals of the course — what should the participants come away with?
* [ ] Create a draft agenda
* [ ] Determine the starting point for the DT knowledge of the participants
* [ ] Decide on the technical level of the participants
* [ ] Create workshops for the participants 

Although this instance of the workshop is geared towards verifiers, some of the content, especially the introductory parts, will be reused for workshops covering each of our services.

**Comment by esune** [comment]
Is this still in todo or can we consider it closed?

**Comment by swcurran** [comment]
Closed.
