### ISSUE TITLE
[EPIC] Schema/cred def/OCA bundle discovery tools

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/DITP#4]
Need a way for an Issuer to use existing schema/OC bundle for their configuration to be able to issue without recreating a new schema/OCA bundle

**Comment by esune** [comment]
@krobinsonca is this still valid or do we want to close it?

**Comment by krobinsonca** [comment]
I think it's still valid. Could be separated though for schema discovery and OCA bundle discovery

**Comment by esune** [comment]
@swcurran @krobinsonca I think this might need to be transferred to the `aries-oca-bundles` repo, if you agree I can get it done.
