### ISSUE TITLE
Create a new Cred Def for IDIM after upgrading to 0.10.0, update Verifier Presentation Requests

### ISSUE THREAD

**Issue by swcurran** [bcgov/DITP#53]
In order to trigger the upgrade to a new Revocation Registry, we have determined that the best approach is to create a new Credential Definition for the Person credential.

We need to determine exactly how to do that.  Presumably, we just set the new CredDef Tag in the Controller configuration and restart the agent, but that has to be verified and documented.  Then, that needs to be applied to IDIM -- in dev, test and prod.

In concert, the verifiers of the IDIM Person credential, such as A2A, needs to be updated to accept the new creddef, along with the old one.

Assigning to @esune to start this one.

**Comment by WadeBarnes** [comment]
Same question here; https://github.com/bcgov/DITP/issues/54#issuecomment-1686666657
