### ISSUE TITLE
Rotate the IDIM RevReg after upgrading to 0.10.0

### ISSUE THREAD

**Issue by swcurran** [bcgov/DITP#55]
After upgrading the IDIM issuer ACA-Py instance to 0.10.0 (0.10.0-rc0 is fine for dev), please rotate the active RegRevs using the new Admin API endpoint for rotation that has been added to `/revocation`.

I assume this will be done via a script/direct call vs. added to the IDIM Issuer Admin User Interface, but I leave that to others to decide.

**Comment by esune** [comment]
Replaced by https://github.com/bcgov/DITP-DevOps/issues/103
