### ISSUE TITLE
Rotate the LSBC RevReg after upgrading to Askar and 0.10.0

### ISSUE THREAD

**Issue by swcurran** [bcgov/DITP#56]
After upgrading the LSBC Issuer ACA-Py instance to 0.10.0 (0.10.0-rc0 is fine for dev), please rotate the active RegRevs using the new Admin API endpoint for rotation that has been added to /revocation.

I assume this will be done via a direct call to the Admin API, but leave those details to you.

**Comment by esune** [comment]
Replaced by https://github.com/bcgov/DITP-DevOps/issues/102
