### ISSUE TITLE
Define reservation form requirements for Traction dev/test/prod and sandbox

### ISSUE THREAD

**Issue by esune** [bcgov/DITP#73]
We need guidelines to configure the optional reservation fields when requesting a tenant, in all of our environments:

- `dev`/`test`/`prod`
- `sandbox`

The current fields don;t seem particularly useful/necessary, so a revamp would be good.
Tenant name and contact email will **always** be required, and cannot be removed.

**Comment by loneil** [comment]
This is complete in the values file (not reflected in Prod yet but next deployment will pick that up)
