### ISSUE TITLE
Experiment with Load Test Generator in preparation for use with IDIM Issuer and a Verifier

### ISSUE THREAD

**Issue by swcurran** [bcgov/DITP#74]
Experiment with the use of the [Load Test Generator]() that is coming via the recent [Code With Us from Indicio](https://marketplace.digital.gov.bc.ca/opportunities/code-with-us/51d7c289-51a8-4307-939c-5a4271c7b2b6).

Link to the load test generator repository: https://github.com/Indicio-tech/aries-akrida
Link to videos describing using the load test generator: https://www.youtube.com/playlist?list=PL3LvHy3eIPsloLj7CZ-9zacG__WCkcmtn

0. Familiarize yourself with the CWU, the load test generator repository/documentation, and the videos created.
1. Initial task is to run the load test generator as locally as possible -- e.g. on a dev box with all of the components running locally: load test generator, mediator, issuer, verifier. Just follow the guidance in the repo and as needed, get help from the Indicio team.
2. Next up, determine from the DITP SRE team from where to run the load test generator in the cloud -- e.g. AWS, Azure or whatever. Get access to such an environment and run a test with the load test generator running remotely and the components under test running locally -- e.g. on the local system or on OpenShift.
   - AFAIK -- the "default" configuration requires the load test generator access and use the issuer and verifier ACA-Py Admin interface to run the tests. That is OK for this exercise, but later we will want to do that a little differently.
3. Plan for and spin up a minimal issuer of credentials controller and a verifier controller to use for testing -- ideally on OpenShift.  Enable an HTTPS route into the controller that the Load Test Generator can use to trigger actions -- a connect/issue, a revoke/reissue, and a verify.  Adjust (with the help of Indicio) how to use the Load Test Generator to do that. Ideally, use the dev or test DITP Mediator for the test. Nice to have -- rerun the test but with the Indicio Public Mediator. Check with the Indicio team on that.
4. Collaborate with the IDIM Issuer team to define how the test will be run with the real Dev/SIT/QA (or whatever) IDIM issuer for the Person Credential, the DITP Mediator and a Dev Verifier.  Identify the changes needed in the code to trigger the actions.

**Comment by gurjmatharu** [comment]
Just commenting some of my findings here:
- Docs: https://github.com/hyperledger/aries-akrida/blob/264270c95c19974ca5f242f9ceed644d998c1687/docs/NONCLUSTERED.md?plain=1#L574
- the docker-compose environment variables need to be set properly.  Just changing them and rerunning docker-compose up may not work.  You may need to `docker-compose down` then `docker-compose up` to confirm env variables are working
- Using traction make sure you update the credentials and bearer token in the .env
- WSL relay issues continue to plague me (hopefully only me) the nginx port for traction doesn't remove itself so I end up getting time outs.  So ensure your ports are open.
- The major issue was ensuring the mediator settings were correct: https://github.com/hyperledger/aries-akrida/blob/264270c95c19974ca5f242f9ceed644d998c1687/docs/NONCLUSTERED.md?plain=1#L578 This meant commenting out line in `agent.js`


Some overall notes the locust agent doesn't have very good error handling - ensure your setup is correct before going into the locust side.

**Comment by gurjmatharu** [comment]
Docs pushed here :point_right: https://github.com/bcgov/aries-load-generator/blob/locust-kt/locust-docs.md
