### ISSUE TITLE
Transition to GH Projects

### ISSUE THREAD

**Issue by esune** [bcgov/DITP#79]
Assess Github projects as issue tracking board for the Enterprise Apps team, start moving towards using it instead of ZenHub.

Note: understand whether cross-organization and cross-repo usage is sustainable, and proceed accordingly

**Comment by WadeBarnes** [comment]
Cross repo links work well in GHP.  Simple matter of pasting the URL of the issue into the title of the issue in GHP.

**Comment by WadeBarnes** [comment]
The link looks like this; 
![image](https://github.com/bcgov/DITP/assets/10504350/59d05dd6-b916-4235-afe0-9ce4c295853f)

and opens up in the side panel like this:
![image](https://github.com/bcgov/DITP/assets/10504350/c027a9d4-dfdd-4d58-b8b4-1b63de9eaa78)

**Comment by esune** [comment]
Closing, as it has been duplicated by #81
